#include "Easy_Menu_User.h"

/* Easy Menu User Configuration File */
/* This file is auto-generated by Easy Menu Builder */
/* Configuration: �����ļ� */

/* USER CODE PUBLIC BEGIN */

#include "oled.h"

void Easy_Menu_Display_Char_Port(unsigned short int x, unsigned short int y, char ch, unsigned char reverse_flag)
{
    OLED_ShowChar(x, y, ch, OLED_6X8);
    if (reverse_flag)
    {
        OLED_ReverseArea(x, y, CHAR_WIDTH, CHAR_HEIGHT);
    }
}

void Easy_Menu_Display_Char_Line_Port(unsigned short int x, unsigned char line, char ch, unsigned char reverse_flag)
{
    Easy_Menu_Display_Char_Port(x, line * CHAR_HEIGHT, ch, reverse_flag);
}

/* USER CODE PUBLIC END */

/* ================================================================= ռλ���� ================================================================= */
struct {
    unsigned char sw1;
    unsigned char sw2;
    unsigned char sw3;
    unsigned char sw4;
    unsigned char uint8_data;
    unsigned short int uint16_data;
    unsigned int uint32_data;
    signed char int8_data;
    signed short int int16_data;
    signed int int32_data;
    float float_data;
    unsigned char hours;
    unsigned char minutes;
    unsigned char seconds;
    unsigned char millisecond;
} Easy_Menu_Ui_Data = {
    .sw1 = 0,
    .sw2 = 0,
    .sw3 = 0,
    .sw4 = 0,
    .uint8_data = 1,
    .uint16_data = 2,
    .uint32_data = 3,
    .int8_data = 4,
    .int16_data = 5,
    .int32_data = 6,
    .float_data = 7.0f,
    .hours = 23,
    .minutes = 59,
    .seconds = 55,
    .millisecond = 0,
};
/* ============================================================== ҳ�桢��Ŀ���� ============================================================== */    
Ordinary_Page main_page;
    Goto_Item main_page_1_item;
    Goto_Item main_page_2_item;
    Goto_Item main_page_3_item;
    Goto_Item main_page_4_item;
    Goto_Item main_page_5_item;
    Goto_Item main_page_6_item;
    Goto_Item main_page_7_item;
    Show_Page start_page;
    Ordinary_Page Text_Page;
        Text_Item Text_Page_1_item;
        Text_Item Text_Page_2_item;
        Text_Item Text_Page_3_item;
        Text_Item Text_Page_4_item;
    Ordinary_Page Switch_Page;
        Switch_Item Switch_Page_1_item;
        Switch_Item Switch_Page_2_item;
        Switch_Item Switch_Page_3_item;
        Switch_Item Switch_Page_4_item;
    Ordinary_Page Data_Page;
        Data_Item Data_Page_1_item;
        Data_Item Data_Page_2_item;
        Data_Item Data_Page_3_item;
        Data_Item Data_Page_4_item;
        Data_Item Data_Page_5_item;
        Data_Item Data_Page_6_item;
        Data_Item Data_Page_7_item;
    Ordinary_Page Enum_Page;
        Enum_Item Enum_Page_1_item;
        Enum_Item Enum_Page_2_item;
    Ordinary_Page User_Show_Page;
        Show_Item User_Show_Page_1_item;
        Show_Item User_Show_Page_2_item;
        Show_Item User_Show_Page_3_item;
        Show_Item User_Show_Page_4_item;
    Ordinary_Page Goto_Page;
        Goto_Item Goto_Page_1_item;
        Goto_Item Goto_Page_2_item;
        Goto_Item Goto_Page_3_item;
        Goto_Item Goto_Page_4_item;
        Ordinary_Page goto_1_page;
            Goto_Item goto_1_page_1_item;
            Ordinary_Page goto_11_page;
                Goto_Item goto_11_page_1_item;
                Ordinary_Page goto_111_page;
                    Text_Item goto_111_page_1_item;
                    Goto_Item goto_111_page_2_item;
        Ordinary_Page goto_3_page;
            Text_Item goto_3_page_1_item;
/* ================================================================= ö���б� ================================================================= */
char *Enum_Page_1_item_enum_str[3] = {
    "Static",
    "Slow",
    "Fast"
};

char *Enum_Page_2_item_enum_str[2] = {
    "Run",
    "Stop"
};

/* ============================================================== �ص���������Ŀ�� ============================================================ */
void Text_Page_2_Item_Callback(char *str)
{
    /* USER CODE BEGIN */

    /* USER CODE END */
}

void Switch_Page_1_Item_Callback(unsigned char data)
{
    /* USER CODE BEGIN */

    /* USER CODE END */
}

void Switch_Page_2_Item_Callback(unsigned char data)
{
    /* USER CODE BEGIN */

    /* USER CODE END */
}

void Switch_Page_3_Item_Callback(unsigned char data)
{
    /* USER CODE BEGIN */

    /* USER CODE END */
}

void Switch_Page_4_Item_Callback(unsigned char data)
{
    /* USER CODE BEGIN */

    /* USER CODE END */
}

void Data_Page_1_Item_Callback(void *data) // *((unsigned char*)data)
{
    /* USER CODE BEGIN */

    /* USER CODE END */
}

void Data_Page_2_Item_Callback(void *data) // *((unsigned short int*)data)
{
    /* USER CODE BEGIN */

    /* USER CODE END */
}

void Data_Page_3_Item_Callback(void *data) // *((unsigned int*)data)
{
    /* USER CODE BEGIN */

    /* USER CODE END */
}

void Data_Page_4_Item_Callback(void *data) // *((signed char*)data)
{
    /* USER CODE BEGIN */

    /* USER CODE END */
}

void Data_Page_5_Item_Callback(void *data) // *((signed short int*)data)
{
    /* USER CODE BEGIN */

    /* USER CODE END */
}

void Data_Page_6_Item_Callback(void *data) // *((signed int*)data)
{
    /* USER CODE BEGIN */

    /* USER CODE END */
}

void Data_Page_7_Item_Callback(void *data) // *((float*)data)
{
    /* USER CODE BEGIN */

    /* USER CODE END */
}

void Enum_Page_1_Item_Callback(char *str)
{
    /* USER CODE BEGIN */

    /* USER CODE END */
}

void Hour_Item_Callback(void)
{
    /* USER CODE BEGIN */
    if(Easy_Menu_Ui_Data.hours >= 24)
    {
        Easy_Menu_Ui_Data.hours = 0;
    }
    /* USER CODE END */
}

void Minute_Item_Callback(void)
{
    /* USER CODE BEGIN */
    if(Easy_Menu_Ui_Data.minutes >= 60) 
    {
        Easy_Menu_Ui_Data.minutes = 0;
        Easy_Menu_Ui_Data.hours++;
    }
    /* USER CODE END */
}

void Second_Item_Callback(void)
{
    /* USER CODE BEGIN */
    if(Easy_Menu_Ui_Data.seconds >= 60) 
    {
        Easy_Menu_Ui_Data.seconds = 0;
        Easy_Menu_Ui_Data.minutes++;
    }
    /* USER CODE END */
}

void Millisecond_Item_Callback(void)
{
    /* USER CODE BEGIN */
    static unsigned int Show_Page_4_Item_Last_Tick = 0;
    
    Easy_Menu_Ui_Data.millisecond += (easy_menu.tick - Show_Page_4_Item_Last_Tick) / 10;

    Show_Page_4_Item_Last_Tick = easy_menu.tick;
    
    if(Easy_Menu_Ui_Data.millisecond >= 100) 
    {
        Easy_Menu_Ui_Data.millisecond = 0;
        Easy_Menu_Ui_Data.seconds++;
    }
    /* USER CODE END */
}

/* ============================================================== �ص�������ҳ�棩 ============================================================ */
/* Private variables ---------------------------------------------------------*/
/* USER CODE VALUE BEGIN */
const char ch[4] = {'|', '/', '-', '\\'};
unsigned char show_page_len = 0;
unsigned char show_page_index = 0;
unsigned char ch_index = 0;
/* USER CODE VALUE END */
/* Private function ----------------------------------------------------------*/
void Start_Page_Enter_Callback(void)
{
    /* USER CODE BEGIN */
    char title[] = "Easy Menu";
    
    if(easy_menu.Display_Char != NULL)
    {
        for(unsigned char i = 0; i < strlen(title); i++)
            easy_menu.Display_Char((SCREEN_WIDTH / 2) - (strlen(title) * CHAR_WIDTH / 2) + i * CHAR_WIDTH, 0, title[i], 0);
        
        easy_menu.Display_Char(CHAR_WIDTH, (SCREEN_HEIGHT / 2) - (CHAR_HEIGHT / 2), '[', 0);
        
        easy_menu.Display_Char(SCREEN_WIDTH - CHAR_WIDTH, (SCREEN_HEIGHT / 2) - (CHAR_HEIGHT / 2), ']', 0);
        
        show_page_len = (SCREEN_WIDTH - CHAR_WIDTH * 3) / CHAR_WIDTH;
        
        for(unsigned char i = 0; i < show_page_len; i++)
            easy_menu.Display_Char(CHAR_WIDTH * 2 + i * CHAR_WIDTH, (SCREEN_HEIGHT / 2) - (CHAR_HEIGHT / 2), '-', 0);
    }
    else if(easy_menu.Display_Char_Line != NULL)
    {
        for(unsigned char i = 0; i < strlen(title); i++)
            easy_menu.Display_Char_Line((SCREEN_WIDTH / 2) - (strlen(title) * CHAR_WIDTH / 2) + i * CHAR_WIDTH, 0, title[i], 0);
        
        easy_menu.Display_Char_Line(CHAR_WIDTH, EASY_MENU_LINE_MAX_NUM / 2, '[', 0);
        
        easy_menu.Display_Char_Line(SCREEN_WIDTH - CHAR_WIDTH, EASY_MENU_LINE_MAX_NUM / 2, ']', 0);
        
        show_page_len = (SCREEN_WIDTH - CHAR_WIDTH * 3) / CHAR_WIDTH;
        
        for(unsigned char i = 0; i < show_page_len; i++)
            easy_menu.Display_Char_Line(CHAR_WIDTH * 2 + i * CHAR_WIDTH, EASY_MENU_LINE_MAX_NUM / 2, '-', 0);
    }
    
    show_page_index = 0;
    ch_index = 0;
    /* USER CODE END */
}

void Start_Page_Period_Callback(void* temp, Easy_Menu_Input_TYPE user_input)
{
    /* USER CODE BEGIN */
    if(easy_menu.Display_Char != NULL)
    {
        easy_menu.Display_Char(0, (SCREEN_HEIGHT / 2) - (CHAR_HEIGHT / 2), ch[ch_index], 0);
        
        for(unsigned char i = 0; i < show_page_index; i++)
        {
            easy_menu.Display_Char(CHAR_WIDTH * 2 + i * CHAR_WIDTH, (SCREEN_HEIGHT / 2) - (CHAR_HEIGHT / 2), '#', 0);
        }
        
         easy_menu.Display_Char(CHAR_WIDTH * 2 + show_page_index * CHAR_WIDTH, (SCREEN_HEIGHT / 2) - (CHAR_HEIGHT / 2), '>', 0);
    }
    else if(easy_menu.Display_Char_Line != NULL)
    {
        easy_menu.Display_Char_Line(0, EASY_MENU_LINE_MAX_NUM / 2, ch[ch_index], 0);
        
        for(unsigned char i = 0; i < show_page_index; i++)
        {
            easy_menu.Display_Char_Line(CHAR_WIDTH * 2 + i * CHAR_WIDTH, EASY_MENU_LINE_MAX_NUM / 2, '#', 0);
        }
        
         easy_menu.Display_Char_Line(CHAR_WIDTH * 2 + show_page_index * CHAR_WIDTH, EASY_MENU_LINE_MAX_NUM / 2, '>', 0);
    }
    
    if(++show_page_index >= show_page_len) 
    {
//        OLED_Clear();
        Easy_Menu_Goto_Page(PAGE(main_page));
    }
    
    if(++ch_index >= 4) ch_index = 0;
    /* USER CODE END */
}

/* =========================================================== �����б�����ͨҳ�棩 =========================================================== */
Item *main_page_items[7] = {
    ITEM(main_page_1_item),
    ITEM(main_page_2_item),
    ITEM(main_page_3_item),
    ITEM(main_page_4_item),
    ITEM(main_page_5_item),
    ITEM(main_page_6_item),
    ITEM(main_page_7_item)
};

Item *Text_Page_items[4] = {
    ITEM(Text_Page_1_item),
    ITEM(Text_Page_2_item),
    ITEM(Text_Page_3_item),
    ITEM(Text_Page_4_item)
};

Item *Switch_Page_items[4] = {
    ITEM(Switch_Page_1_item),
    ITEM(Switch_Page_2_item),
    ITEM(Switch_Page_3_item),
    ITEM(Switch_Page_4_item)
};

Item *Data_Page_items[7] = {
    ITEM(Data_Page_1_item),
    ITEM(Data_Page_2_item),
    ITEM(Data_Page_3_item),
    ITEM(Data_Page_4_item),
    ITEM(Data_Page_5_item),
    ITEM(Data_Page_6_item),
    ITEM(Data_Page_7_item)
};

Item *Enum_Page_items[2] = {
    ITEM(Enum_Page_1_item),
    ITEM(Enum_Page_2_item)
};

Item *User_Show_Page_items[4] = {
    ITEM(User_Show_Page_1_item),
    ITEM(User_Show_Page_2_item),
    ITEM(User_Show_Page_3_item),
    ITEM(User_Show_Page_4_item)
};

Item *Goto_Page_items[4] = {
    ITEM(Goto_Page_1_item),
    ITEM(Goto_Page_2_item),
    ITEM(Goto_Page_3_item),
    ITEM(Goto_Page_4_item)
};

Item *goto_1_page_items[1] = {
    ITEM(goto_1_page_1_item)
};

Item *goto_11_page_items[1] = {
    ITEM(goto_11_page_1_item)
};

Item *goto_111_page_items[2] = {
    ITEM(goto_111_page_1_item),
    ITEM(goto_111_page_2_item)
};

Item *goto_3_page_items[1] = {
    ITEM(goto_3_page_1_item)
};

/* ================================================================ ϵͳ��ʼ�� ================================================================ */
void Easy_Menu_Ui_Init(void)
{
    Ordinary_Page_Init(NULL, PAGE(main_page), "Main", main_page_items, 7);
        Goto_Item_Init(PAGE(main_page), ITEM(main_page_1_item), "Start page", PAGE(start_page));
        Goto_Item_Init(PAGE(main_page), ITEM(main_page_2_item), "Text Page", PAGE(Text_Page));
        Goto_Item_Init(PAGE(main_page), ITEM(main_page_3_item), "Switch_Page", PAGE(Switch_Page));
        Goto_Item_Init(PAGE(main_page), ITEM(main_page_4_item), "Data_Page", PAGE(Data_Page));
        Goto_Item_Init(PAGE(main_page), ITEM(main_page_5_item), "Enum_Page", PAGE(Enum_Page));
        Goto_Item_Init(PAGE(main_page), ITEM(main_page_6_item), "Show_Page", PAGE(User_Show_Page));
        Goto_Item_Init(PAGE(main_page), ITEM(main_page_7_item), "Goto_Page", PAGE(Goto_Page));
    Show_Page_Init(PAGE(main_page), PAGE(start_page), "Start page", 150, Start_Page_Enter_Callback, Start_Page_Period_Callback, NULL);
    Ordinary_Page_Init(PAGE(main_page), PAGE(Text_Page), "Text Page", Text_Page_items, 4);
        Text_Item_Init(PAGE(Text_Page), ITEM(Text_Page_1_item), "Welcome", NULL);
        Text_Item_Init(PAGE(Text_Page), ITEM(Text_Page_2_item), "Github:", Text_Page_2_Item_Callback);
        Text_Item_Init(PAGE(Text_Page), ITEM(Text_Page_3_item), "https://github.com/", NULL);
        Text_Item_Init(PAGE(Text_Page), ITEM(Text_Page_4_item), "2549850807/Easy_Menu", NULL);
    Ordinary_Page_Init(PAGE(main_page), PAGE(Switch_Page), "Switch_Page", Switch_Page_items, 4);
        Switch_Item_Init(PAGE(Switch_Page), ITEM(Switch_Page_1_item), "LED1", &Easy_Menu_Ui_Data.sw1, Switch_Page_1_Item_Callback);
        Switch_Item_Init(PAGE(Switch_Page), ITEM(Switch_Page_2_item), "LED2", &Easy_Menu_Ui_Data.sw2, Switch_Page_2_Item_Callback);
        Switch_Item_Init(PAGE(Switch_Page), ITEM(Switch_Page_3_item), "LED3", &Easy_Menu_Ui_Data.sw3, Switch_Page_3_Item_Callback);
        Switch_Item_Init(PAGE(Switch_Page), ITEM(Switch_Page_4_item), "LED4", &Easy_Menu_Ui_Data.sw4, Switch_Page_4_Item_Callback);
    Ordinary_Page_Init(PAGE(main_page), PAGE(Data_Page), "Data_Page", Data_Page_items, 7);
        Data_Item_Init(PAGE(Data_Page), ITEM(Data_Page_1_item), "uint8_t data", UNSIGNED_CHAR, &Easy_Menu_Ui_Data.uint8_data, UNSIGNED_CHAR_VAL(1), 1, UNSIGNED_CHAR_VAL(0), 0, UNSIGNED_CHAR_VAL(0), 0, Data_Page_1_Item_Callback);
        Data_Item_Init(PAGE(Data_Page), ITEM(Data_Page_2_item), "uint16_t data", UNSIGNED_SHORT_INT, &Easy_Menu_Ui_Data.uint16_data, UNSIGNED_SHORT_INT_VAL(1), 1, UNSIGNED_SHORT_INT_VAL(0), 0, UNSIGNED_SHORT_INT_VAL(0), 0, Data_Page_2_Item_Callback);
        Data_Item_Init(PAGE(Data_Page), ITEM(Data_Page_3_item), "uint32_t data", UNSIGNED_INT, &Easy_Menu_Ui_Data.uint32_data, UNSIGNED_INT_VAL(1), 1, UNSIGNED_INT_VAL(0), 0, UNSIGNED_INT_VAL(0), 0, Data_Page_3_Item_Callback);
        Data_Item_Init(PAGE(Data_Page), ITEM(Data_Page_4_item), "int8_t data", SIGNED_CHAR, &Easy_Menu_Ui_Data.int8_data, SIGNED_CHAR_VAL(1), 1, SIGNED_CHAR_VAL(0), 0, SIGNED_CHAR_VAL(0), 0, Data_Page_4_Item_Callback);
        Data_Item_Init(PAGE(Data_Page), ITEM(Data_Page_5_item), "int16_t data", SIGNED_SHORT_INT, &Easy_Menu_Ui_Data.int16_data, SIGNED_SHORT_INT_VAL(1), 1, SIGNED_SHORT_INT_VAL(0), 0, SIGNED_SHORT_INT_VAL(0), 0, Data_Page_5_Item_Callback);
        Data_Item_Init(PAGE(Data_Page), ITEM(Data_Page_6_item), "int32_t data", SIGNED_INT, &Easy_Menu_Ui_Data.int32_data, SIGNED_INT_VAL(1), 1, SIGNED_INT_VAL(0), 0, SIGNED_INT_VAL(0), 0, Data_Page_6_Item_Callback);
        Data_Item_Init(PAGE(Data_Page), ITEM(Data_Page_7_item), "float data", FLOAT, &Easy_Menu_Ui_Data.float_data, FLOAT_VAL(0.1), 1, FLOAT_VAL(-10), 1, FLOAT_VAL(10), 1, Data_Page_7_Item_Callback);
    Ordinary_Page_Init(PAGE(main_page), PAGE(Enum_Page), "Enum_Page", Enum_Page_items, 2);
        Enum_Item_Init(PAGE(Enum_Page), ITEM(Enum_Page_1_item), "Mode", Enum_Page_1_item_enum_str, 3, Enum_Page_1_Item_Callback);
        Enum_Item_Init(PAGE(Enum_Page), ITEM(Enum_Page_2_item), "State", Enum_Page_2_item_enum_str, 2, NULL);
    Ordinary_Page_Init(PAGE(main_page), PAGE(User_Show_Page), "Show_Page", User_Show_Page_items, 4);
        Show_Item_Init(PAGE(User_Show_Page), ITEM(User_Show_Page_1_item), "Hour", UNSIGNED_CHAR, &Easy_Menu_Ui_Data.hours, 10, Hour_Item_Callback);
        Show_Item_Init(PAGE(User_Show_Page), ITEM(User_Show_Page_2_item), "Minute", UNSIGNED_CHAR, &Easy_Menu_Ui_Data.minutes, 10, Minute_Item_Callback);
        Show_Item_Init(PAGE(User_Show_Page), ITEM(User_Show_Page_3_item), "Second", UNSIGNED_CHAR, &Easy_Menu_Ui_Data.seconds, 10, Second_Item_Callback);
        Show_Item_Init(PAGE(User_Show_Page), ITEM(User_Show_Page_4_item), "Millisecond", UNSIGNED_CHAR, &Easy_Menu_Ui_Data.millisecond, 10, Millisecond_Item_Callback);
    Ordinary_Page_Init(PAGE(main_page), PAGE(Goto_Page), "Goto_Page", Goto_Page_items, 4);
        Goto_Item_Init(PAGE(Goto_Page), ITEM(Goto_Page_1_item), "Goto 1 Page", PAGE(goto_1_page));
        Goto_Item_Init(PAGE(Goto_Page), ITEM(Goto_Page_2_item), "Goto Page 2", NULL);
        Goto_Item_Init(PAGE(Goto_Page), ITEM(Goto_Page_3_item), "Goto 3 Page", PAGE(goto_3_page));
        Goto_Item_Init(PAGE(Goto_Page), ITEM(Goto_Page_4_item), "Goto Page 4", NULL);
    Ordinary_Page_Init(PAGE(Goto_Page), PAGE(goto_1_page), "Goto 1 Page", goto_1_page_items, 1);
        Goto_Item_Init(PAGE(goto_1_page), ITEM(goto_1_page_1_item), "Goto 11 Page", PAGE(goto_11_page));
    Ordinary_Page_Init(PAGE(goto_1_page), PAGE(goto_11_page), "Goto 11 Page", goto_11_page_items, 1);
        Goto_Item_Init(PAGE(goto_11_page), ITEM(goto_11_page_1_item), "Goto 111 Page", PAGE(goto_111_page));
    Ordinary_Page_Init(PAGE(goto_11_page), PAGE(goto_111_page), "Goto 111 Page", goto_111_page_items, 2);
        Text_Item_Init(PAGE(goto_111_page), ITEM(goto_111_page_1_item), "Hello World!!!", NULL);
        Goto_Item_Init(PAGE(goto_111_page), ITEM(goto_111_page_2_item), "Home", PAGE(main_page));
    Ordinary_Page_Init(PAGE(Goto_Page), PAGE(goto_3_page), "Goto 3 Page", goto_3_page_items, 1);
        Text_Item_Init(PAGE(goto_3_page), ITEM(goto_3_page_1_item), "TEST", NULL);
    
    Easy_Menu_Goto_Page(PAGE(main_page));
}
